<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
	<TargetFramework>net8.0-windows</TargetFramework>
	<UseWindowsForms>true</UseWindowsForms>
    <UseWPF>false</UseWPF>
    <Nullable>disable</Nullable>
    <ApplicationIcon>AppIcon.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <AssemblyName>Fenceless</AssemblyName>
    <RootNamespace>Fenceless</RootNamespace>
    <AssemblyTitle>Fenceless</AssemblyTitle>
    <AssemblyDescription>Open Source Alternative to 'Stardock Fences'</AssemblyDescription>
    <AssemblyProduct>Fenceless</AssemblyProduct>
    <AssemblyCopyright>Copyright © Damianttje 2025</AssemblyCopyright>
    <AssemblyVersion>10.0</AssemblyVersion>
    <FileVersion>10.0</FileVersion>
    <Platforms>AnyCPU;x86</Platforms>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='Debug'">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
	<OutputPath>bin\Debug\</OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='Release'">
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <DefineConstants>TRACE</DefineConstants>
	<OutputPath>bin\Release\</OutputPath>
	<SelfContained>true</SelfContained>


	  <Version>1.2.3.0</Version>
	  <FileVersion>$(Version)</FileVersion>
	  <AssemblyVersion>$(Version)</AssemblyVersion>
	  <InformationalVersion>$(Version)</InformationalVersion>
	  
	  <Deterministic>true</Deterministic>
	  <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
	  <PublishDir>bin\release\BestFences_single</PublishDir>

	  <RuntimeIdentifier>win-x64</RuntimeIdentifier>
	  <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>

	  <PublishSingleFile>true</PublishSingleFile>

	  <IncludeAllContentForSelfExtract>true</IncludeAllContentForSelfExtract>
	  <SelfContained>true</SelfContained>

	  <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>

	  <Optimize>False</Optimize>

	  <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
















  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DarkModeUI" Version="3.1.0" />
    <PackageReference Include="Microsoft.Toolkit.Uwp.Notifications" Version="7.1.3" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="AppIcon.ico" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Util\LnkHelper.cs" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>




	<Target Name="AutoPublishOnReleaseBuild" AfterTargets="Build" Condition=" '$(Configuration)' == 'Release' ">
		<Message Importance="high" Text="start auto publish..." />
		<Exec Command="dotnet publish -c Release --no-build -p:Deterministic=true" />
	</Target>





	<!-- auto zip exe files -->
	<Target Name="ZipPublishedFiles" AfterTargets="AutoPublishOnReleaseBuild" Condition=" '$(Configuration)' == 'Release' ">
		<Message Importance="high" Text="begin zip file..." />

		<PropertyGroup>
			<CurrentVersion Condition="'$(Version)' == ''">1.0.0.0</CurrentVersion>
			<CurrentVersion Condition="'$(Version)' != ''">$(Version)</CurrentVersion>

			<PublishOutputDir>$(MSBuildProjectDirectory)\bin\release\BestFences_single</PublishOutputDir>

			<ZipFileName>BestFences_single_V$(CurrentVersion).zip</ZipFileName>
			<ZipFilePath>$(MSBuildProjectDirectory)\bin\release\$(ZipFileName)</ZipFilePath>
		</PropertyGroup>

		<Message Importance="high" Text="check publish path: $(PublishOutputDir)" />
		<Message Condition="Exists($(PublishOutputDir))" Importance="high" Text="path exist,ver: $(CurrentVersion)" />
		<Warning Condition="!Exists($(PublishOutputDir))" Text="path not exist: $(PublishOutputDir)" />

		<ItemGroup>
			<FilesToZip Include="$(PublishOutputDir)\**\*.*" />
		</ItemGroup>

		<ZipDirectory Condition="Exists($(PublishOutputDir))" SourceDirectory="$(PublishOutputDir)" DestinationFile="$(ZipFilePath)" Overwrite="true" />

		<Message Condition="Exists($(ZipFilePath))" Importance="high" Text="end zipped: $(ZipFilePath)" />
		<Warning Condition="!Exists($(ZipFilePath))" Text="failed zippde: $(ZipFilePath)" />
	</Target>
	
	
</Project>