//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fenceless {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TrayMenu {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TrayMenu() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fenceless.TrayMenu", typeof(TrayMenu).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Add Fence 的本地化字符串。
        /// </summary>
        internal static string MenuAddFence {
            get {
                return ResourceManager.GetString("MenuAddFence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit 的本地化字符串。
        /// </summary>
        internal static string MenuExit {
            get {
                return ResourceManager.GetString("MenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fences Size 的本地化字符串。
        /// </summary>
        internal static string MenuFencesSize {
            get {
                return ResourceManager.GetString("MenuFencesSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hide All 的本地化字符串。
        /// </summary>
        internal static string MenuHideAll {
            get {
                return ResourceManager.GetString("MenuHideAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Normal Fence 的本地化字符串。
        /// </summary>
        internal static string MenuNormalFence {
            get {
                return ResourceManager.GetString("MenuNormalFence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Organize desktop files 的本地化字符串。
        /// </summary>
        internal static string MenuOrganizeDesktopFiles {
            get {
                return ResourceManager.GetString("MenuOrganizeDesktopFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        internal static string MenuSettings {
            get {
                return ResourceManager.GetString("MenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show All 的本地化字符串。
        /// </summary>
        internal static string MenuShowAll {
            get {
                return ResourceManager.GetString("MenuShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Size Auto 的本地化字符串。
        /// </summary>
        internal static string MenuSizeAuto {
            get {
                return ResourceManager.GetString("MenuSizeAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Size Center 的本地化字符串。
        /// </summary>
        internal static string MenuSizeCenter {
            get {
                return ResourceManager.GetString("MenuSizeCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Size Left 的本地化字符串。
        /// </summary>
        internal static string MenuSizeLeft {
            get {
                return ResourceManager.GetString("MenuSizeLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Size Right 的本地化字符串。
        /// </summary>
        internal static string MenuSizeRight {
            get {
                return ResourceManager.GetString("MenuSizeRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Size TopRight 的本地化字符串。
        /// </summary>
        internal static string MenuSizeTopRight {
            get {
                return ResourceManager.GetString("MenuSizeTopRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start with Windows 的本地化字符串。
        /// </summary>
        internal static string MenuStartwithWindows {
            get {
                return ResourceManager.GetString("MenuStartwithWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View L ogs 的本地化字符串。
        /// </summary>
        internal static string MenuViewLogs {
            get {
                return ResourceManager.GetString("MenuViewLogs", resourceCulture);
            }
        }
    }
}
